name: Close PR if not from development branch

on:
  pull_request:
    types: [opened, edited] 

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check branch names
        run: |
          if [ ${{ github.head_ref }} != "development" ]; then
            echo "::error::Pull request must be from the development branch"
            exit 1
          fi
          if [ ${{ github.base_ref }} != "development" ]; then
            echo "::error::Pull request must be merged into the development branch"
            exit 1
          fi
     
