name: PHPCS Check

on:
  pull_request:
    types: [opened, edited] 


jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with specific version of PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.3'
      - name: Install Composer dependencies
        run: |
          composer install

      - name: Check PHP code with PHPCS
        run: ./wp-content/themes/glide-basetheme/vendor/bin/phpcs --standard=WordPress ./wp-content/themes/glide-basetheme
