name: PHPCS Check

on:
  pull_request:
    types: [opened, edited] 


jobs:
  phpcs:
    runs-on: ubuntu-latest
    php: '8.2.3'

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar install --no-progress --no-suggest  --working-dir=wp-content/themes/glide-basetheme

      - name: Check PHP code with PHPCS
        run: ./wp-content/themes/glide-basetheme/vendor/bin/phpcs --standard=WordPress ./wp-content/themes/glide-basetheme
