name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
  - name: init
    - uses: actions/checkout@v3
  - name: Zip section-container
    run: |
      cd wp-content/plugins
      zip -r section-container.zip section-container
  - name: Create Release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ".gitignore,sw.js,wp-content/themes/glide-basetheme.zip,wp-content/plugins/section-container.zip"
        bodyFile: "README.md"
