name: Create Release with Zip Archive

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  release:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.PAT }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
          .gitignore
          sw.js
